export const ERROR_CODES = {
    INVALID_REQUEST: "INVALID_REQUEST",

    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_TOKEN: "INVALID_TOKEN",

    FORBIDDEN: "FORBIDDEN",
    ORDER_HISTORY_ACCESS_DENIED: "ORDER_HISTORY_ACCESS_DENIED",

    USER_NOT_FOUND: "USER_NOT_FOUND",

    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;